version: 1.0
workflows:
  - name: annotate_functional_variants
    subclass:  WDL
    primaryDescriptorPath: /workflows/combined_gnomad_clinvar/variant_workflow.wdl
    authors:
      - name: Allison Cheney
        email: archeney@ucsc.edu
  - name: merge_clinical_data
    subclass:  WDL
    primaryDescriptorPath: /workflows/combined_gnomad_clinvar/merge_clinical_functional_data.wdl
    authors:
      - name: Allison Cheney
        email: archeney@ucsc.edu
  - name: get_gnomad_variants
    subclass: WDL
    primaryDescriptorPath: /workflows/get_gnomad_variants.wdl
    authors:
      - name : Allison Cheney, Melissa Cline
        email: mcline@ucsc.edu
  - name: get_clinvar_variants
    subclass: WDL
    primaryDescriptorPath: /workflows/combined_gnomad_clinvar/get_clinvar_variants.wdl
    authors:
      - name: Allison Cheney
        email: archeney@ucsc.edu
