include required(classpath("application"))

backend {
  default = Local
  providers {
    Local {
      actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
      config {
        run-in-background = true
        runtime-attributes = """
        Int? docker_memory_gb
        Int? docker_cpu
        String? docker
        """
        submit-docker = """
        docker run \
          --cidfile ${docker_cid} \
          -i \
          --memory=7g \
          --cpus=2 \
          --entrypoint ${job_shell} \
          -v ${cwd}:${docker_cwd} \
          ${docker} ${docker_script}
        """
      }
    }
  }
}

system {
  io {
    per-workflow-cache-size = 10000
  }
}
